name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.5.0"

   
      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Generate documentation
        run: |
          cd client
          npm run docs

      - name: Run tests
        run: |
          cd client
          npm test
      - name: create a test file
        run: |
          cd client
          touch fichierTest.txt
      
