name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.5.0"

   
      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Generate documentation
        run: |
          cd client
          npm run docs

      - name: Run tests
        run: |
          cd client
          npm test
      - name: Commit and push documentation
        env:
          GITHUB_TOKEN: ${{ secrets.P_A_T }} 
        run: |
          cd client
          git config --local user.email "afdalbouraima2@gmail.com"
          git config --local user.name "Bouraima"
          git add docs/
          git commit -m "Mise à jour de la documentation"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Afdal-B/Planning_Poker.git HEAD:main      
