name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du repository
      uses: actions/checkout@v4

    - name: Installation Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Installation des packages
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/server" >> $GITHUB_ENV
    
    - name: Lancement des tests
      run: |
        source venv/bin/activate
        pytest ./server/tests/
